    let sections = document.querySelectorAll("section");
    let navLinks = document.querySelectorAll("nav .categories a");

    window.onscroll = () => {
    let scrollPosition = window.scrollY;
    sections.forEach((section) => {
        let offsetTop = section.offsetTop - 50;
        let offsetBottom = offsetTop + section.offsetHeight;

        if (scrollPosition >= offsetTop && scrollPosition < offsetBottom) {
        let id = section.getAttribute("id");
        navLinks.forEach((link) => {
            link.addEventListener("click", (e) => {
            navLinks.forEach((nav) => nav.classList.remove("active"));
            e.currentTarget.classList.add("active");
            });
        });
        }
    });
    };

    document.addEventListener("DOMContentLoaded", () => {
    // Create the description page overlay
    let desPage = document.createElement("div");
    desPage.id = "descrPage";
    desPage.style.display = "none";
    desPage.style.position = "fixed";
    desPage.style.top = "0";
    desPage.style.left = "0";
    desPage.style.width = "100%";
    desPage.style.height = "100%";
    desPage.style.backgroundColor = "rgba(0, 0, 0, 0.8)";
    desPage.style.zIndex = "100";
    desPage.style.color = "white";
    desPage.style.fontSize = "16px";
    desPage.style.textAlign = "center";
    desPage.style.borderRadius = "10px";

    // Create content container inside the overlay
    let desContent = document.createElement("div");
    desContent.style.padding = "20px";
    desContent.style.textAlign = "left";

    // Add description text
    let descriptionText = document.createElement("p");
    desContent.appendChild(descriptionText);

    // Add close button
    const closeButton = document.createElement("button");
    closeButton.textContent = "Close";
    closeButton.style.position = "absolute";
    closeButton.style.top = "85%";
    closeButton.style.left = "47%";
    closeButton.style.marginTop = "20px";
    closeButton.style.padding = "10px 20px";
    closeButton.style.background = "rgb(11, 242, 142)";
    closeButton.style.color = "black";
    closeButton.style.border = "none";
    closeButton.style.borderRadius = "5px";
    closeButton.style.cursor = "pointer";
    closeButton.addEventListener("click", () => {
        desPage.style.display = "none";
    });

    desContent.appendChild(closeButton);
    desPage.appendChild(desContent);
    document.body.appendChild(desPage);

    // Descriptions for the images
    let descriptions = {
        "LaCasaDePapelBig.jpg":
        '<h2>La Casa De Papel...</h2> The Story: follows a mysterious man known as "The Professor" who is preparing for the biggest heist ever committed. It is essentially the dream of his father, who was unable to achieve it because he was shot dead by the police during one of his robberies. The Professor recruits 8 individuals, each with a codename based on a major global city. These individuals have criminal backgrounds, are wanted by the authorities, and have nothing to lose. The plan is to break into the Spanish Royal Mint and print 2.4 billion euros. To accomplish this, they must stay inside for 11 days, manage 67 hostages, and deal with an elite Spanish police force.' +
        "The story begins with Tokyo waking up from a dream and heading to her mother's house to say goodbye before traveling to China, as she is wanted by the police. Unbeknownst to her, the police are listening to her call and planning to arrest her. On her way to her mother's house, which is a police trap, a red car pulls up, and a mysterious man convinces her not to go, whom she later calls her \"guardian angel.\" He offers her a job: to steal 2.4 billion euros. Tokyo agrees and goes with him to a remote house, where she and the other eight people will spend five months training for the heist on the Spanish Royal Mint.<br><br>At the beginning of the series, the viewer believes that the goal of the heist is money, but as the story progresses, the true backstory of the heist is revealed. It turns out that Professor Sergio Marquina spent half his life planning it. The story begins with young Sergio, who is sick in the United States and needs money for his treatment to avoid being discharged from the hospital. Because of this, his father tries to rob a bank in America, but he is shot during the attempt. Later, Sergio recovers and begins planning everything with his brother (Berlin), who has been with him from the start. Sergio plans every detail, relying on the stories his father used to tell him about heists, which he later learns were true, as his father had actually carried them out." +
        "The planning for the heist began with digging a tunnel from his external base five years before the heist was executed, with the goal of stealing 2.4 billion euros. He studied the potential and expected behavior of the police, the laws, the judicial system, and its loopholes. He devised numerous plans, such as the Trojan Horse plan, the Valencia plan, the Cameroon plan, the last-resort failure plan that was never used, the media plan, and the negotiation delay plan, as they needed time to print the 2.4 billion and thus aimed to stall for 10-12 days.<br><br>The Most Prominent Actors: <br>Alvaro Morte (Professor)<br> Sergio Marquina (Silva)<br> Ursula Corbero (Tokyo)<br> Alba Flores (Nairobi)<br> Paco Tos (Moscow)<br> Miguel Herrán (Rio)<br> Pedro Alonso (Berlin)<br> Jaime Llorente (Denver)<br><br> Rating: La Casa de Papel (Money Heist) generally receives a 8/10 .",
        "TheWalkingBig.jpg":
        '<h2>The Walking Dead...</h2><br> The events of The Walking Dead take place after a contagious virus spreads worldwide, turning people into the undead (referred to as "walkers" or "biters"). These walkers hunt down living humans and animals, trying to eat them. They are attracted by sounds and the scent of humans. Anyone who is bitten or scratched by a walker becomes infected and gradually turns into one. At the beginning of the series, it\'s mentioned that all living humans carry the virus, and once they die, they become walkers. The only way to kill a walker is to destroy the brain or completely damage the body, such as by burning it.<br><br>The series premiered in the United States on October 31, 2010, exclusively on AMC. It was broadcast worldwide on the Fox International Channels, and in the Arab world, it aired simultaneously on the Fox TV channel. Based on its ratings and high viewership, AMC renewed the series for another season every year since its debut. Starting from its third season, the series attracted the highest number of viewers aged 18-49 compared to any other television program. The eleventh and final season of the series aired on August 22, 2021.<br><br> The story centers around Deputy Sheriff Rick Grimes, who wakes up from a coma to find the world in ruins. Rick becomes the leader of a group of survivors fleeing the city of Atlanta in the state of Georgia, trying to protect each other and stay alive by any means possible.<br><br> ' +
        "The Most Prominent Actors:<br> Norman Reedus (Daryll)<br> Laurie Holden (Andrea)<br> Andrew Lincoln (Rick Grimes)<br> Sarah Wayne Callies (Lori Grimes)<br> Lauren Cohen (Maggie Greaney)<br> Scott Wilson (Harshel Greene)<br> Jon Bernthal (Shane Walsh)<br> Chandler Riggs (Carl Grimes)<br><br> Rating: The Walking Dead generally receives a 8/10 .",
        "prison-break-big.jpg":
        "<h2>Prison Break...</h2><br> \"Prison Break\" is an American television series created by writer and director Paul Scheuring. Its four seasons aired on the Fox network from August 29, 2005, to May 15, 2009, while the fifth season aired from April 4 to May 30, 2017. The series follows the story of two brothers: one who is sentenced to death for a crime he did not commit, and the other who devises a detailed plan to help his brother escape from prison and clear his record. The series was produced by Adelstein-Parouse Productions, in collaboration with Original Film and 20th Century Fox Television. The series' music, composed by Ramin Djawadi, was nominated for an Emmy Award in 2006.<br><br> In 2003, Fox Network rejected the series, expressing concerns and a lack of confidence in the success of long-running shows. However, after the success of similar series like Lost and 24, Fox changed its mind. In 2004, the network decided to support the production and preparation of the series. The first season received positive reviews and performed well in the ratings. Initially, the first season was planned to consist of thirteen episodes, but due to its popularity, it was extended to include nine additional episodes. Prison Break was nominated for several awards, including the 2005 Golden Globe Award for Best Drama Series and the 2006 People's Choice Award for Favorite New TV Drama, both of which it won.<br><br>Story about Lincoln Burrows is convicted of a murder he did not commit, and now he is awaiting his execution on Fox River Prison. Michael Schofield, his only brother will do anything to get him out. By deliberately causing a crime that will get Michael put on the same prison as his brother, he plans to break them both out.<br><br>" +
        "The Most Prominent Actors: <br> Wentworth Miller (Michael Scofield)<br> Dominic Purcell (Lincoln Burrows)<br>Robert Knepper (T-Bag)<br> Amaury Nolasco (Fernando Sucre)<br>William Mapother (Chris Franco)<br>Sarah Wayne Callies (Sara Tancredi)<br>Paul Adelstein (Paul Kellerman)<br>Marshall Allman (L.J. Burrows)<br> Rockmond Dunbar (C-Note)<br><br> Rating: Prison Break generally receives a 8/10 .",
        "the-boys-big.webp":
        '<h2>The Boys...</h2><br>"The Boys" is an American web television series in the superhero and black comedy genre, based on the comic book series of the same name by Garth Ennis and Darick Robertson. The series was developed by Eric Kripke and premiered on July 26, 2019, on Amazon Prime Video. It was renewed for a second season before the first season even aired, and the third season premiered on June 2, 2022.<br><br>On September 26, 2018, the official poster for the series was released. On October 5, 2018, along with the show\'s panel at the annual New York Comic Con, a trailer for the series was released. On January 24, 2019, another trailer was released via Seth Rogen\'s official Twitter account. The series premiered on July 26, 2019, after another teaser. On July 22, Slipknot released a new song titled "Solway Firth" accompanied by a music video featuring audio clips from the show. On June 26, 2020, it was announced that the second season would begin on September 4, 2020, with the first three episodes available immediately, and the rest would air weekly. The official trailer for season two was released on August 4, 2020.A short film titled *The Butcher* was released between seasons one and two on September 10, 2020, with Karl Urban reprising his role as Billy Butcher. Characters from *The Boys* also appeared in a *Death Battle* episode sponsored by Prime Video, which was released on September 17, 2020.<br><br> In a world where superpowers have become commonplace, a group of superheroes works for a corporation that markets them in various fields such as rescue operations, filmmaking, gaming, etc., earning billions of dollars. However, money and privileges corrupt the superheroes, and most of them succumb to their dark impulses. As a result, a group of ordinary people decides to take a stand against these corrupted superheroes.<br><br> The Most Prominent Actors:<br>' +
        "Karl Urban (Billy Butcher)<br>Jack Quaid (Hughie Campbell)<br>Antony Starr (Homelander)<br>Elizabeth Shue (Madelyn Stillwell)<br>Chace Crawford (The Deep)<br>Dominique McElligott (Queen Maeve)<br>Tomer Kapon (Frenchie)<br><br><br> Rating: The Boys generally receives a 8.7/10 .",
        "the_night_agentBig.webp":
        "<h2>The Night Agent...</h2><br> The Night Agent is an American action thriller television series created by Shawn Ryan based on the novel of the same name by Matthew Quirk. Starring Gabriel Basso in the title role, it premiered on Netflix on March 23, 2023. The series emerged as the third-most-viewed debuting series on Netflix in its first four days, and within a week it was renewed for a second season. Within a month, it became the streaming service's sixth-most-viewed series. In October 2024, ahead of the second-season premiere, the series was renewed for a third season. The second season is slated to be released on January 23, 2025.<br><br> FBI agent Peter Sutherland is thrown into a vast conspiracy about a mole at the highest levels of the United States government. To save the nation, he plunges into a desperate hunt for the traitor, while protecting former tech CEO Rose Larkin from the people who murdered her aunt and uncle.<br><br> The first season was filmed in British Columbia, Canada, with the city of Vancouver standing in for Washington, D.C. Filming for the second season began on February 5, 2024 in New York City, with additional filming in Thailand and Washington D.C. It was announced on June 17, 2024, that the second season had concluded filming. <br><br> The Most Prominent Actors:<br>Gabriel Basso (Peter Sutherland)<br>Luciane Buchanan (Rose Larkin)<br>Derrick R. Hinson (Darryl)<br>Fola Evans-Akingbola (Chelsea Arrington)<br>Sarah Desjardins (Maddie)<br>Hong Chau (Diane Farr)<br>Ben Cotton (Nash)<br><br> Rating: The Night Agent generally receives a 7.5/10 .",
        "theLastKingDom-big.jpg":
        "<h2>The Last Kingdom...</h2><br> The Last Kingdom is a British historical drama television series created and developed for television by Stephen Butchard, based on The Saxon Stories series of novels by Bernard Cornwell. The series premiered on 10 October 2015 on BBC Two. After co-producing the second series, Netflix acquired the series in 2018. The series concluded on 9 March 2022 after five series for a total of 46 episodes. A feature-length sequel that concluded the series story, titled Seven Kings Must Die, premiered on 14 April 2023 on Netflix.<br><br> The film Seven Kings Must Die adapts Cornwell's thirteenth and final novel of The Saxon Stories, War Lord, and includes elements of the twelfth novel Sword of Kings, giving a final sendoff to Uhtred of Bebbanburg. The film covers the year 937 and deals with the fallout following the death of King Edward as his disputed heir Aethelstan seizes the throne of England and ignites a war with an alliance of Kings that decides the future of England. The film was written by Martha Hillier and directed by Edward Bazalgette. It premiered on Netflix on 14 April 2023. <br><br> The main events of the reign of Alfred the Great and his heirs are well recorded, and a number of men called Uhtred ruled from Bamburgh Castle, most notably Uhtred the Bold more than a century later. The people identified as \"Danes\" came from many places in and around Denmark, including Southern Sweden and Norway. Historians believe that the Danish invaders of Northumbria came from Jutland in Denmark, as mentioned in Cornwell's books, as well as some of the Danish islands and East Denmark (present-day southern Sweden).<br><br>The Most Prominent Actors:<br>Alexander Dreymon (Uhtred of Bebbanburg)<br>David Dawson (King Alfred the Great)<br>Emily Cox (Brida)<br>Toby Regbo (Aethelred)<br>Rupert Graves (Lord Aethelwold)<br>Mark Rowley (Finan)<br>Arnas Fedaravicius (Sihtric)<br><br> Rating: The Last Kingdom generally receives a 7.5/10 .",
        "Derry-Girls-big.webp":
        "<h2>Derry Girls...</h2><br>Derry Girls is a British period teen sitcom set in Northern Ireland, created and written by Lisa McGee, that premiered on 4 January 2018 on Channel 4 and ran for three series. The channel's most successful comedy since Father Ted, the series was inspired by McGee's own experiences growing up in Derry, Northern Ireland, in the 1990s, during the final years of the Troubles. It stars Saoirse-Monica Jackson, Louisa Harland, Nicola Coughlan, Jamie-Lee O'Donnell, and Dylan Llewellyn as five teenagers living in mid-1990s Derry while attending Our Lady Immaculate College, a fictional girls' Catholic secondary school based on the real-life Thornhill College, where McGee herself studied. Produced by British production company Hat Trick Productions, Derry Girls was filmed in Northern Ireland, with most scenes shot on location in Derry and some in Belfast.<br><br>Although the plot lines of Derry Girls are fictional, the series frequently references actual events of the Troubles and the Northern Ireland peace process, including the 1994 IRA ceasefire announcement, the 1995 visit to Northern Ireland of President Bill Clinton and First Lady Hillary Clinton, and the Good Friday referendum of 1998. Archival footage relating to key political figures such as Ian Paisley, Gerry Adams, Martin McGuinness, John Hume and Mo Mowlam is shown via TV and radio broadcasts in family homes. The soundtrack features popular music of the era, by acts including Ace of Base, Blur, Cypress Hill, Salt-N-Pepa, Enya, the Corrs, Boyzone, Scarlet, Fatboy Slim, PJ & Duncan, and the Cranberries.<br><br>The first series, broadcast on Channel 4 in January and February 2018, became the most-watched series in Northern Ireland since modern records began in 2002. The series was renewed shortly after the pilot episode aired, and the second series was broadcast in March and April 2019. A third and final series set in 1996 and 1997 was commissioned for 2020, although filming was delayed due to the COVID-19 pandemic impact on television production, and premiered in April 2022. A final special extended 45-minute episode titled \"The Agreement\", set in 1998 during the signing of the Good Friday Agreement, aired on 18 May 2022.<br><br>The Most Prominent Actors:<br>Saoirse-Monica Jackson (Erin Quinn)<br>Louisa Harland (Orla McCool)<br>Nicola Coughlan (Clare Devlin)<br>Jamie-Lee (Michelle Mallon)<br>Dylan Llewellyn (James Maguire)<br>Tommy Tiernan (Gerry Quinn)<br><br> Rating: Deery Girls generally receives a 8.5/10 .",
        "fubar-big.jpg":
        "<h2>Fubar...</h2><br> FUBAR is an American action comedy television series created by Nick Santora for Netflix. It stars Arnold Schwarzenegger in his first leading role in a scripted live-action television series and is produced by Skydance Television and Blackjack Films. The series premiered on May 25, 2023. In June 2023, the series was renewed for a second season.<br><br> Luke Brunner and his daughter Emma have lied to each other for years, with neither of them knowing that the other is a CIA operative. Once they both learn the truth, they realize that they do not actually know anything about each other. They are required by their superiors to work together on dangerous operations, leading to challenges when Luke treats Emma as a child and when he becomes overly concerned for her safety and relationship conflicts.<br><br>Skydance Television first announced that it was developing an untitled spy television series for Arnold Schwarzenegger to star in and make his scripted live-action television debut in August 2020. Shortly afterward, Monica Barbaro was cast as the lead opposite Schwarzenegger in the series where a father and daughter are both CIA officers, unbeknownst to the other. Netflix won the rights for the project that November and had ordered eight episodes of the series by May 2021. The cast was expanded in April 2022, announcing several regular and recurring roles. Phil Abraham was announced as director and executive producer of the pilot episode in May, and a July casting announcement added Adam Pally. While in production, the series used the working titles Utap and FUBAR.<br><br>The Most Prominent Actors:<br>Arnold Schwarzenegger (Luke Brunner)<br>Monica Barbaro (Emma Brunner)<br>Milan Carter (Barry Putt)<br>Travis Van Winkle (Aldon Reece)<br>Fortune Feimster (Roo Russell)<br>Fabiana Udenio (Tally Brunner)<br>Gabriel Luna (Boro Polonia)<br><br>Rating: Fubar generally receives a 7/10 .",
        "seinfeld-big.jpg":
        '<h2>Seinfeld...</h2><br> Seinfeld (saɪnfɛld/ SYNE-feld) is an American television sitcom created by Larry David and Jerry Seinfeld that originally aired on NBC from July 5, 1989, to May 14, 1998, with a total of nine seasons consisting of 180 episodes. Its ensemble cast stars Seinfeld as a fictionalized version of himself and focuses on his personal life with three of his friends: best friend George Costanza (Jason Alexander), former girlfriend Elaine Benes (Julia Louis-Dreyfus), and neighbor from across the hall, Cosmo Kramer (Michael Richards).<br><br>Seinfeld is set mostly in and around the titular character\'s apartment in Manhattan\'s Upper West Side in New York City. It has been described as "a show about nothing", often focusing on the minutiae of daily life. Interspersed in all episodes of the first seven seasons are moments of stand-up comedy from the fictional Jerry Seinfeld, frequently related to the episode\'s events.<br><br>As a rising comedian in the late 1980s, Jerry Seinfeld was presented with an opportunity to create a show with NBC. He asked Larry David, a fellow comedian and friend, to help create a premise for a sitcom. The series was produced by West-Shapiro Productions and Castle Rock Entertainment and distributed by Columbia Pictures Television. It was largely written by David and Seinfeld along with scriptwriters. A favorite among critics, the series led the Nielsen ratings in Seasons 6 and 9 and finished among the top two (along with ER of the same network) every year from 1994 to 1998. Only two other shows—I Love Lucy and The Andy Griffith Show—finished their runs at the top of the ratings.<br><br>Seinfeld is widely regarded as one of the greatest and most influential shows of all time. It has been ranked among television\'s best shows in publications such as Entertainment Weekly, Rolling Stone, and TV Guide. Its most renowned episodes include "The Chinese Restaurant", "The Soup Nazi", "The Parking Garage", "The Marine Biologist", and "The Contest". In 2013, the Writers Guild of America voted it the second best-written TV series of all time (second to The Sopranos).[10] E! named it the "Number 1 reason [why] the \'90s ruled". Quotes from numerous episodes have become catchphrases in popular culture.<br><br>The Most Prominent Actors:<br>Jerry Seinfeld (Jerry Seinfeld)<br>Jason Alexander (George Costanza)<br>Julia Louis-Dreyfus (Elaine Benes)<br>Michael Richards (Cosmo Kramer)<br>Wayne Knight (Newman)<br>Jerry Stiller (Frank Costanza)<br><br>Rating: Seinfeld generally receives a 8.8/10 .',
        "tedLasso-big.avif":
        "<h2>Ted Lasso...</h2><br>Ted Lasso (læsoʊ/ LASS-oh) is an American sports comedy-drama television series developed by Jason Sudeikis, Bill Lawrence, Brendan Hunt, and Joe Kelly, based on a character Sudeikis portrayed in a series of promotional media for NBC Sports's coverage of England's Premier League.<br><br>The show follows Ted Lasso, an American college football coach who is hired to coach an English soccer team whose owner secretly hopes his inexperience will lead it to failure, but whose folksy, optimistic leadership proves unexpectedly successful.<br><br>The series has received critical acclaim, with particular praise for its performances (notably Sudeikis, Hannah Waddingham, Phil Dunster, Brett Goldstein, and Juno Temple), humor, writing, themes, and uplifting tone. Among other accolades, its first season was nominated for 20 Primetime Emmy Awards, becoming the most nominated first-season comedy in Emmy history. Sudeikis, Waddingham, and Goldstein won for their performances, and the series won the 2021 Primetime Emmy Award for Outstanding Comedy Series. Sudeikis also won the Golden Globe Award for Best Actor – Television Series Musical or Comedy and the Screen Actors Guild Award for Outstanding Performance by a Male Actor in a Comedy Series. The series repeated all three of those awards the next year.<br><br>The first season of 10 episodes premiered on Apple TV+ on August 14, 2020. The first three episodes were released at once, followed by weekly installments of the remaining seven. A second season of 12 episodes premiered July 23, 2021. In October 2020, it was renewed for a third season of 12 episodes, which premiered March 15, 2023.<br><br>The Most Prominent Actors:<br>Ted Lasso (Jason Sudeikis)<br>Rebecca Welton (Hannah Waddingham)<br>Roy Kent (Brett Goldstein)<br>Jamie Tartt (Phil Dunster)<br>Keeley Jones (Juno Temple)<br>Sam Obisanya (Toheeb Jimoh)<br><br>Rating: Ted Lasso generally receives a 8.8/10 .",
        "theOffice-big.jpg":
        "<h2>The Office...</h2><br> The Office is an American mockumentary sitcom television series based on the 2001–2003 BBC series of the same name created by (and starring) Ricky Gervais and Stephen Merchant. Adapted for NBC by Greg Daniels, a veteran writer for Saturday Night Live, King of the Hill, and The Simpsons, the show depicts the everyday work lives of the office employees at Scranton, Pennsylvania, branch of the fictional Dunder Mifflin Paper Company, and aired from March 24, 2005, to May 16, 2013, with a total of nine seasons consisting of 201 episodes.[1] The show was co-produced by Daniels' Deedle-Dee Productions, Reveille Productions (later Shine America) and 3 Arts Entertainment (although uncredited) in association with Universal Television. The original executive producers were Daniels, Gervais, Merchant, Howard Klein and Ben Silverman, with numerous others being promoted in later seasons.<br><br>Like its British counterpart, the series was filmed in a single-camera setup without a studio audience or a laugh track, to mirror the look of an actual documentary. It debuted on NBC as a mid-season replacement and ended its nine-season run on May 16, 2013, with a two-part series finale. Its original main cast was Steve Carell, Rainn Wilson, John Krasinski, Jenna Fischer, and B. J. Novak. It experienced numerous changes to its ensemble cast during its run. Stars outside the original main cast include Ed Helms, Rashida Jones, Amy Ryan, Mindy Kaling, Craig Robinson, James Spader, Ellie Kemper, and Catherine Tate.<br><br>The Office received moderately positive reviews from critics (except for the pilot episode which received mixed reviews) during its short first season, but the following seasons, particularly Carell's performance, received significant acclaim from television critics as the show's characters, content, structure, and tone diverged considerably from the original British series. These seasons were included on several critics' year-end top TV series lists, winning several awards including a Peabody Award in 2006, two Screen Actors Guild Awards, a Golden Globe Award for Carell's performance, and four Primetime Emmy Awards, including one for Outstanding Comedy Series, in 2006. The eighth season was criticized for declining quality, with Carell's departure in season seven seen as a contributing factor. However, the ninth and final season ended the series with a generally positive response. The series finale, which originally aired on May 16, 2013, was viewed by an estimated 5.7 million viewers and garnered critical acclaim. In 2016, Rolling Stone named The Office one of the 100 greatest television shows of all time.<br><br>The Most Prominent Actors:<br>Michael Scott (Steve Carell)<br>Jim Halpert (John Krasinski)<br>Pam Beesly (Jenna Fischer)<br>Dwight Schrute (Rainn Wilson)<br>Ryan Howard (B.J. Novak)<br><br>Rating: The Office generally receives a 8.9/10 .",
        "theUmbrellaAcademy-big.webp":
        "<h2>The Umbrella Academy...</h2><br> The Umbrella Academy is an American superhero comedy-drama television series based on the comic book series of the same name written by Gerard Way, illustrated by Gabriel Bá, and published by Dark Horse Comics. Created for Netflix by Steve Blackman and developed by Jeremy Slater, it revolves around a dysfunctional family of adopted sibling superheroes who reunite for their father's funeral and the threat of an imminent apocalypse. The series is produced by Borderline Entertainment (season 1–2), Irish Cowboy (season 3), Dark Horse Entertainment, and Universal Content Productions. Netflix gave seasons 1 and 2 a TV-14 rating, while seasons 3 and 4 received a TV-MA rating<br><br>The cast features Elliot Page, Tom Hopper, David Castañeda, Emmy Raver-Lampman, Robert Sheehan, Aidan Gallagher, Cameron Britton, Mary J. Blige, John Magaro, Adam Godley, Colm Feore, Justin H. Min, Ritu Arya, Yusuf Gatewood, Marin Ireland, Kate Walsh, Genesis Rodriguez, and Britne Oldford. The adaptation began development as a film optioned by Universal Pictures in 2011. It was eventually shelved in favor of a television series in 2015, before being officially greenlit by Netflix in July 2017. The series was filmed in Toronto and Hamilton, Ontario.<br><br>The first season was released on Netflix on February 15, 2019. In April 2019, Netflix reported that 45 million households had watched season one during its first month of release, thus becoming one of the most-streamed series of the year. The second and third seasons subsequently followed on July 31, 2020, and June 22, 2022, respectively. In August 2022, the series was renewed for a fourth and final season, which was released on August 8, 2024.<br><br>The first three seasons received positive reviews from critics, while the final season was met with a more mixed reception. The series has received a number of accolades, including six Emmy nominations.<br><br>The Most Prominent Actors:<br>Vanya Hargreeves (Elliot Page)<br>Luther Hargreeves (Tom Hopper)<br>Diego Hargreeves (David Castañeda)<br>Allison Hargreeves (Emmy Raver-Lampman)<br>Klaus Hargreeves (Robert Sheehan)<br><br>Rating: The Umbrella Academy generally receives a 8/10 .",
        "Bridgerton-big.jpg":
        "<h2>Bridgerton...</h2><br>Bridgerton is an American historical romance television series created by Chris Van Dusen for Netflix. Based on the book series by Julia Quinn, it is Shondaland's first scripted show for Netflix. The series is set during the early 1800s in an alternative London Regency era, in which George III established racial equality and granted many people of African descent aristocratic titles due to the African heritage of his wife, Queen Charlotte. The viewer is taken to observe the highly competitive social season; where young marriageable nobility and gentry are introduced into society.<br><br>The first season debuted on December 25, 2020. The second season premiered on March 25, 2022. The third season was across two parts, which premiered on May 16 and June 13, 2024, respectively. The series was renewed for a fourth season in April 2021. The fourth season will be released in 2026. In May 2023, Queen Charlotte: A Bridgerton Story, a spin-off series focused on Queen Charlotte, was released.<br><br>Bridgerton was positively received for its direction, actors' performances, production and set design, winning two Primetime Creative Arts Emmy Awards, a Make-Up Artists And Hair Stylists Guild Awards, and nominations at the Primetime Emmy Awards, Screen Actors Guild Awards, Satellite Awards and NAACP Image Awards. The music score by Kris Bowers earned a Grammy Award nomination for Best Score Soundtrack for Visual Media.<br><br>Set against the backdrop of the Regency era, the eight close-knit siblings of the noble and powerful Bridgerton family – Anthony, Benedict, Colin, Daphne, Eloise, Francesca, Gregory, and Hyacinth – navigate London high society in search of love, surrounded by friends and rivals alike.<br><br>The Most Prominent Actors:<br>Daphne Bridgerton (Phoebe Dynevor)<br>Simon Basset, Duke of Hastings (Regé-Jean Page)<br>Anthony Bridgerton (Jonathan Bailey)<br>Penelope Featherington (Nicola Coughlan)<br>Lady Danbury (Adjoa Andoh)<br>Queen Charlotte (Golda Rosheuvel)<br><br>Rating: Bridgerton generally receives a 7.3/10 .",
        "my-lady-jane-big.jpg":
        "<h2>My Lady Jane...</h2><br>My Lady Jane (titled My Queen Jane on screen for episodes four through six) is a historical fantasy romance television series made for Amazon Prime Video, starring Emily Bader as the titular character. Produced by MacDonald & Parkes, the television series is adapted by Gemma Burgess from a novel by Jodi Meadows, Brodi Ashton, and Cynthia Hand that provides a fantasy reimagining of the life of Lady Jane Grey.<br><br>All episodes of the series were released on June 27, 2024. In August that year, Amazon cancelled My Lady Jane after one season. The cancellation inspired backlash and a petition, including from fantasy author and A Song of Ice and Fire creator George R.R. Martin.<br><br>In an alternate 16th-century England, Lady Jane Grey is coerced by her mother into marrying Lord Guildford Dudley. Jane, as cousin to Edward VI, is in line to the throne. The world of My Lady Jane is inhabited by Ethians, humans who can take animal form, as well as ordinary humans, known as Verity. In England, the Verity ruling class have driven Ethians out of society; in response, Ethians have formed a group called the Pack.<br><br>The Most Prominent Actors:<br>Lady Jane Grey (Emily Bader)<br>King Edward VI (Edward Bluemel)<br>Gifford Dudley (Jordan Peters)<br>Mary Tudor (Inès Spiridonov)<br>John Dudley (Dominic Cooper)<br>Bess of Hardwick (Bel Powley)<br><br>Rating: Bridgerton generally receives a 7.4/10 .",
        "Outlander-big.jpg":
        "<h2>Out Lander...</h2><br>Outlander is a historical drama television series based on the Outlander novel series by Diana Gabaldon. Developed by Ronald D. Moore, the show premiered on August 9, 2014, on Starz. It stars Caitríona Balfe as Claire Randall, a former World War II military nurse in Scotland who, in 1945, finds herself transported back in time to 1743. There she encounters, falls in love with and marries a dashing Highland warrior named Jamie Fraser (Sam Heughan), a tacksman of Gabaldon's fictionalized version of Clan Fraser of Lovat. Here, Claire becomes embroiled in the Jacobite rising.<br><br>The 16-episode first season of the television series (released as two half-seasons) is based on the first novel in the series, Outlander. The second season of 13 episodes, based on Dragonfly in Amber, aired from April to July 2016. The 13-episode third season, based on Voyager, aired from September to December 2017. The 13-episode fourth season, based on Drums of Autumn, aired from November 2018 to January 2019. The fifth season of 12 episodes, based on The Fiery Cross, aired from February to May 2020. The sixth season of 8 episodes, based on A Breath of Snow and Ashes, aired from March to May 2022. The seventh season, which consists of 16 episodes, is based on An Echo in the Bone and premiered on June 16, 2023.<br><br>By February 2022, development had begun on a prequel series titled Outlander: Blood of My Blood, which will focus on Jamie Fraser's parents Brian and Ellen Fraser. In January 2023, Outlander: Blood of My Blood was officially confirmed for a ten-episode first season, and Outlander was renewed for a ten-episode eighth and final season.<br><br>The Most Prominent Actors:<br>Claire Fraser (Caitríona Balfe)<br>Jamie Fraser (Sam Heughan)<br>Frank Randall / Jonathan \"Black Jack\" Randall (Tobias Menzies)<br>Brianna Randall Fraser (Sophie Skelton)<br>Roger Wakefield MacKenzie (Richard Rankin)<br>Murtagh Fraser (Duncan Lacroix)<br><br>Rating: Bridgerton generally receives a 8.4/10 .",
        "the_Good_Place_big.jpg":
        "<h2>The Good Place...</h2><br>The Good Place is an American fantasy-romantic television series created by Michael Schur. It premiered on NBC on September 19, 2016, and concluded on January 30, 2020, after four seasons and 53 episodes.<br><br>Although the plot evolves significantly over the course of the series, the initial premise of the series follows Eleanor Shellstrop (Kristen Bell), a dead woman who is placed in a Heaven-esque utopian afterlife designed and supervised by afterlife \"architect\" Michael (Ted Danson). However, Eleanor knows she did not deserve to get into the Good Place, as she led a dishonorable life. To avoid being found out and sent to the Bad Place, Eleanor attempts to hide her morally imperfect past behavior while trying to become a more ethical person. William Jackson Harper, Jameela Jamil, and Manny Jacinto co-star as other residents of the Good Place, with D'Arcy Carden as Janet, an artificial being who assists the residents.<br><br>The Good Place received critical acclaim for its originality, writing, acting, setting, and tone. The first season's twist ending and the show's exploration and creative use of ethics and philosophy were specifically praised. Among its accolades, the series received a Peabody Award and four Hugo Awards for Best Dramatic Presentation, Short Form. It was nominated for 14 Primetime Emmy Awards, including Outstanding Comedy Series for its third and fourth seasons.<br><br>The series is centered on an afterlife in which humans are sent to \"the Good Place\" or \"the Bad Place\" after death. All humans are assigned a numerical score based on the morality of their conduct in life, and only those with the very highest scores are sent to the Good Place, where they enjoy eternal happiness with their every wish granted, guided by an artificial intelligence named Janet; all others experience an eternity of torture in the Bad Place.<br><br>The Most Prominent Actors:<br>Eleanor Shellstrop (Kristen Bell)<br>Chidi Anagonye (William Jackson Harper)<br>Tahani Al-Jamil (Jameela Jamil)<br>Jason Mendoza (Manny Jacinto)<br>Michael (Ted Danson)<br>Janet (D\'Arcy Carden)<br><br>Rating: Bridgerton generally receives a 8.2/10 .",
        "the90show.big.jpg":
        "<h2>That 90s Show...</h2><br>The first season of That '90s Show released onto Netflix on January 19, 2023. The second season was divided into two parts, with the first eight episodes having been released on June 27, 2024, and another eight episodes being released on August 22, 2024 after it was originally set to be released on October 24. The first half of the episodes of season 2 have been released as \"Part 2\" the second half was released as \"Part 3\" of the show.<br><br>That '90s Show is an American teen sitcom that serves as the sequel to That '70s Show. Set during the summer of 1995 and 1996, featuring characters and locales that debuted in its predecessor, it debuted on Netflix on January 19, 2023. In February 2023, the series was renewed for a second season, with the first part of the season released on June 27, 2024, and the second part released on August 22, 2024. In October 2024, the series was canceled after an extended second season.<br><br>The show centers on Leia Forman, the teenage daughter of Eric Forman and Donna Pinciotti, forming bonds with other teenagers as she spends the summer of 1995 with her grandparents Red and Kitty in Point Place, Wisconsin.<br><br>The Most Prominent Actors:<br>Leia Forman (Callie Haverda)<br>Eric Forman (Topher Grace)<br>Donna Pinciotti (Laura Prepon)<br>Red Forman (Kurtwood Smith)<br>Kitty Forman (Debra Jo Rupp)<br>Jay Kelso (Mace Coronel)<br><br>Rating: That 90s Show generally receives a 6.5/10 .",
        "you-big.webp":
        "<h2> You...</h2><br>You is an American psychological thriller television series based on the books by Caroline Kepnes, developed by Greg Berlanti and Sera Gamble, and produced by Berlanti Productions, Alloy Entertainment, and A+E Studios in association with Warner Horizon Television, now Warner Bros. Television.<br><br>The first season, which is based on the novel You, premiered on Lifetime in September 2018, and follows Joe Goldberg, a bookstore manager and serial killer who falls in love and develops an extreme obsession. The season stars Penn Badgley, Elizabeth Lail, Luca Padovan, Zach Cherry, and Shay Mitchell. Lifetime announced in July 2018 that You had been renewed for a second season, based on Kepnes' follow-up novel Hidden Bodies. The series later moved to Netflix and the second season was released in December 2019. The season follows Joe as he moves to Los Angeles and falls in love with local heiress Love Quinn. For the second season, Ambyr Childers was upgraded to a series regular, joining newly cast Victoria Pedretti, James Scully, Jenna Ortega, and Carmela Zumbado.<br><br>In January 2020, the series was renewed for a third season by Netflix, which was released on October 15, 2021. In the third season, Saffron Burrows was upgraded to a series regular, joining newly cast Travis Van Winkle, Shalita Grant, Tati Gabrielle, and Dylan Arnold. In October 2021, ahead of the third-season premiere, the series was renewed for a fourth season, which was released over two parts on February 9 and March 9, 2023. The season also stars Charlotte Ritchie, Tilly Keeper, Amy-Leigh Hickman, Ed Speleers and Lukas Gage. In March 2023, the series was renewed for a fifth and final season.<br><br>The Most Prominent Actors:<br>Joe Goldberg (Penn Badgley)<br>Guinevere Beck (Elizabeth Lail)<br>Love Quinn (Victoria Pedretti)<br>Marienne Bellamy (Tati Gabrielle)<br>Ellie Alves (Jenna Ortega)<br>Forty Quinn (James Scully)<br><br>Rating: You generally receives a 7.7/10 .",
        "adams-big.jpg":
        "<h2> John Adams...</h2><br>John Adams is a 2008 American television miniseries chronicling U.S. Founding Father and president John Adams's political life and his role in the founding of the United States. The miniseries was directed by Tom Hooper and starred Paul Giamatti in the title role. Kirk Ellis wrote the screenplay based on the 2001 book John Adams by David McCullough.<br><br>The biopic of Adams and the story of the first 50 years of the United States was broadcast in seven parts by HBO between March 16 and April 20, 2008. John Adams received widespread critical acclaim and many prestigious awards. The show won four Golden Globe awards and thirteen Emmy awards, more than any other miniseries in history.<br><br>In 1770 John Adams is a respected lawyer in his mid-30s known for his dedication to the law and justice. After the Boston Massacre happens, Adams arrives at the scene and is subsequently sought as a defense counsel for the soldiers involved by their commander, Captain Thomas Preston, who asks him to defend them in court. Reluctant at first, he agrees despite knowing this will antagonize his neighbors and friends. Adams is depicted to have taken the case because he believed everyone deserves a fair trial and he wanted to uphold the standard of justice.<br><br>Adams' cousin Samuel Adams is one of the main colonists opposed to the Intolerable Acts passed by the Parliament of Great Britain. He is one of the executive members of the Sons of Liberty, an organization dedicated to resisting the acts. Adams is depicted as a studious man doing his best to defend his clients. The show also illustrates Adams' appreciation and respect for his wife, Abigail. In one scene, Adams is shown having his wife proofread his summation as he takes her suggestions. After many sessions in court, the jury returns a verdict of not guilty of murder for each defendant, thanks to Adams' arguments. Additionally, the episode illustrates the growing tension over the Intolerable Acts, and Adams' election to the First Continental Congress.<br><br>The Most Prominent Actors:<br>John Adams (Paul Giamatti)<br>Abigail Adams (Laura Linney)<br>Thomas Jefferson (Stephen Dillane)<br>Benjamin Franklin (Tom Wilkinson)<br>John Quincy Adams (Ebon Moss-Bachrach)<br>George Washington (David Morse)<br><br>Rating: John Adams generally receives a 8.5/10 .",
        "rome-big.jpg":
        "<h2> Rome...</h2><br>Rome is an American-British historical drama television series released in 2005–2007 and created by John Milius, William J. MacDonald, and Bruno Heller. The series is set in the 1st century BC, during Ancient Rome's transition from Republic to Empire. The series features a sprawling cast of characters, many based on real figures from historical records, but the lead protagonists are ultimately two soldiers named Lucius Vorenus and Titus Pullo, who find their lives intertwined with key historical events.<br><br>An international co-production between the United States, the United Kingdom and Italy, the series was filmed in various locations, but most notably in the Cinecittà studios in Rome, Italy. The show, consisting of two seasons for a total of 22 episodes, aired on HBO, and BBC Two from 28 August 2005 to 25 March 2007, and was later released on DVD and Blu-ray.<br><br>Rome received largely positive reviews and had a high number of viewers. It received substantial media attention from the start, becoming a ratings success for HBO and the BBC (although the numbers declined considerably in the second season) and being honoured with numerous awards, including four Emmy Awards, seven Primetime Emmy Awards, and a Visual Effects Society Award. The series ran for two seasons out of the planned five due to high production cost; much of the material for the third and fourth seasons was telescoped into the second season. Accordingly, the series has been praised for high detail of accuracy and scenery of its daily life, including both its Roman and Egyptian language used in the script.<br><br>The series primarily chronicles the lives and deeds of the rich, powerful, and historically significant, but it also focuses on the lives, fortunes, families, and acquaintances of two common men: Lucius Vorenus and Titus Pullo, fictionalized versions of a pair of Roman soldiers mentioned in Caesar's Commentarii de Bello Gallico. The fictional Vorenus and Pullo manage to witness and often influence many of the historical events presented in the series, although some dramatic license is taken.<br><br>The Most Prominent Actors:<br>Lucius Vorenus (Kevin McKidd)<br>Titus Pullo (Ray Stevenson)<br>Atia of the Julii (Polly Walker)<br>Gaius Octavian (Maxim Baldry)<br>Julius Caesar (Ciarán Hinds)<br>Cleopatra (Lyndsey Marshal)<br><br>Rating: Rome generally receives a 8.7/10 .",
        "the-pacific-big.jpeg":
        "<h2> The Pacific...</h2><br>The Pacific is a 2010 American war drama miniseries produced by HBO, Playtone, and DreamWorks that premiered in the United States on March 14, 2010.<br><br>The series is a companion piece to the 2001 miniseries Band of Brothers and focuses on the United States Marine Corps's actions in the Pacific Theater of Operations within the wider Pacific War. Whereas Band of Brothers followed the men of Easy Company of the 506th Parachute Infantry Regiment through the European Theater, The Pacific centers on the experiences of three Marines (Robert Leckie, Eugene Sledge, and John Basilone) who were in different regiments (1st, 5th, and 7th, respectively) of the 1st Marine Division.<br><br>The Pacific was spearheaded by Bruce C. McKenna (co-executive producer), one of the main writers on Band of Brothers. Hugh Ambrose, the son of Band of Brothers author Stephen Ambrose, was a project consultant.<br><br>The Pacific miniseries features the 1st Marine Division's battles in the Pacific, such as Guadalcanal, Cape Gloucester, Peleliu, and Okinawa, as well as Basilone's involvement in the Battle of Iwo Jima. It is based primarily on the memoirs of two US Marines: With the Old Breed: At Peleliu and Okinawa by Eugene Sledge and Helmet for My Pillow by Robert Leckie. It also draws on Sledge's memoir China Marine and Red Blood, Black Sand, the memoir of Chuck Tatum, a Marine who fought alongside Basilone at Iwo Jima.<br><br>The Most Prominent Actors:<br>Eugene \"Sledge\" Sledge (Joseph Mazzello)<br>Robert Leckie (James Badge Dale)<br>Dale Dye (Colonel Chesty Puller)<br>John Basilone (Jon Seda)<br>Sid Phillips (Shane Meadows)<br>George Luz (Martin McCann)<br><br>Rating: The Pacific generally receives a 8.3/10 .",
        "usa-exp-big.jpg":
        "<h2> American Experiance...</h2><br>American Experience is a television program airing on the Public Broadcasting Service (PBS) in the United States. The program airs documentaries, many of which have won awards, about important or interesting events and people in American history.<br><br>The series premiered on October 4, 1988, and was originally titled The American Experience. It was shortened to American Experience during a rebrand and image update. The show has had a presence on the internet since 1995, and more than 100 American Experience programs are accompanied by their own internet websites, which provide background information on the subjects covered as well as teachers' guides and educational companion materials. The show is produced primarily by WGBH-TV in Boston, Massachusetts, though occasionally in the early seasons it was co-produced by other PBS stations such as WNET (Channel 13) in New York City.<br><br>Some programs considered part of the American Experience collection were produced prior to the creation of the series. Vietnam: A Television History was one of them, airing originally in 1983 after taking six years to assemble. Also, in 2006, American Experience rebroadcast Eyes on the Prize: America's Civil Rights Years, the first half of the 1986 documentary series about the Civil Rights Movement of the 1950s and 1960s.<br><br>The Most Prominent Actors:<br>Wendell Pierce (Narrator, various episodes)<br>David McCullough (Historian and author, frequent contributor)<br>Ken Burns (Director of historical documentaries, frequent collaborator)<br>Dorothy Height (Civil rights leader, featured in episodes)<br>Lyndon B. Johnson (Featured in episodes about U.S. Presidents)<br>Franklin D. Roosevelt (Featured in episodes about U.S. Presidents)<br><br>Rating: American Experience generally receives a 8.8/10 .",
        "usa-story-big.jpg":
        "<h2> America The Story of Us...</h2><br>America: The Story of Us (also internationally known as America: The Story of the U.S.) is a 12-part, 9-hour documentary-drama television miniseries that premiered on April 25, 2010, on History. Produced by Nutopia, the program portrays more than 400 years of American history (with emphasis on how American creation of new technologies has had effects on the nation's history and, by implication, the world). It spans time from the successful English settlement of Jamestown beginning in 1607, through to the present day. Narrated by Liev Schreiber (Danny Webb for the international version), the series recreates many historical events by using actors dressed in the style of the period and computer-generated special effects. The miniseries received mixed reviews by critics; but it attracted the largest audiences of any special aired by the channel to date.<br><br>The documentary received a 60% approval rating from Metacritic.com. Many criticized the series for having too many \"celebrities\" express their opinions about the United States, rather than having historians provide more insight and data about particular periods and events.<br><br>Critics praised the series' willingness to grapple with some of the difficult issues in US history, including African slavery, racial segregation and the genocide of the Native Americans. Mary McNamara, of the Los Angeles Times, wrote that \"'America: The Story of Us' seems to draw its inspiration from Fox's '24' and the E! Channel.\" She continues, \"[I]n the first hour, producer Jane Root seems more enamored of her ability to conjure, in glorious CG, the lifecycle of a tobacco plant or the brick-by-brick construction of New Amsterdam than anything so dull as explaining the complexities of actual history.\"<br><br>The Most Prominent Actors:<br>George Washington (Narrated by various historians, featured throughout)<br>Thomas Jefferson (Narrated by various historians, featured in episodes)<br>Abraham Lincoln (Narrated by various historians, featured in episodes)<br>Benjamin Franklin (Narrated by various historians, featured in episodes)<br>John Adams (Narrated by various historians, featured in episodes)<br>Andrew Jackson (Narrated by various historians, featured in episodes)<br><br>Rating: America The Story of Us generally receives a 8.5/10 .",
        "vikings-big.jpg":
        "<h2> Vikings...</h2><br>Vikings is a historical drama television series created and written by Michael Hirst. A co-production between Canada and Ireland, the series originally aired on the History Channel, premiering on 3 March 2013 and concluding on 30 December 2020, when the second half of the sixth season was released in its entirety on Amazon Prime Video in Ireland, ahead of its broadcast on History in Canada from January 1 to March 3, 2021. A sequel series, titled Vikings: Valhalla, premiered on Netflix on February 25, 2022.<br><br>It is inspired by the sagas of Ragnar Lodbrok, a Viking who is one of the best-known legendary Norse heroes and notorious as the scourge of Anglo-Saxon England and West Francia. The show portrays Ragnar as a farmer from the Kattegat who rises to fame by raiding England and eventually becomes a Scandinavian king, with the support of his family and fellow warriors. In the later seasons, the series follows the fortunes of his sons and their adventures in England, Scandinavia, Kievan Rus', the Mediterranean and North America.<br><br>The series's principal cast features Travis Fimmel as Lothbrok, alongside Katheryn Winnick, Clive Standen, Jessalyn Gilsig, Gustaf Skarsgård, Gabriel Byrne, George Blagden, Donal Logue, Alyssa Sutherland, Linus Roache, and Alexander Ludwig. The series was filmed entirely in Ireland, on-location in County Wicklow and at Ashford Studios.<br><br>The series is inspired by the tales of the Norsemen of early medieval Scandinavia. It broadly follows the exploits of the legendary Viking chieftain Ragnar Lothbrok and his crew, family and descendants, as notably laid down in the 13th-century sagas Ragnars saga Loðbrókar and Ragnarssona þáttr, as well as in Saxo Grammaticus' 12th-century work Gesta Danorum. Norse legendary sagas were partially fictional tales based in the Norse oral tradition, written down about 200 to 400 years after the events they describe. Further inspiration is taken from historical sources of the period, such as records of the Viking raid on Lindisfarne depicted in the second episode, or Ahmad ibn Fadlan's 10th-century account of the Varangians. The series begins at the start of the Viking Age, marked by the Lindisfarne raid in 793.<br><br>Ragnar Lothbrok (Travis Fimmel)<br>Lagertha (Katheryn Winnick)<br>Rollo (Clive Standen)<br>Bjorn Ironside (Alexander Ludwig)<br>Floki (Gustaf Skarsgård)<br>Ivar the Boneless (Alex Høgh Andersen)<br><br>Rating: Vikings generally receives a 8.5/10 .",
        };

    // Add click event listeners to all big images
    let bigImgs = document.querySelectorAll(".big");

    bigImgs.forEach((image) => {
        image.addEventListener("click", () => {
        let imgName = image.src.split("/").pop();
        let description = descriptions[imgName] || "No description available.";
        descriptionText.innerHTML = description;
        desPage.style.display = "flex";
        });
    });
    });
